module Stomper
  module Frames
    # Encapsulates a "MESSAGE" server side frame for the Stomp Protocol.
    #
    # See the {Stomp Protocol Specification}[http://stomp.codehaus.org/Protocol]
    # for more details.
    class Message < Stomper::Frames::ServerFrame
      # This class is the factory for all MESSAGE frames received.
      factory_for :message

      # Creates a new message frame with the given +headers+ and +body+
      def initialize(headers, body)
        super('MESSAGE', headers, body)
      end

      # Returns the message id generated by the stomp broker.
      #
      # This is a convenience method for:
      # frame.headers[:'message-id'] or frame.headers['message-id']
      def id
        @headers[:'message-id']
      end

      # Returns the destination from which this message was delivered.
      #
      # This is a convenience method for:
      # frame.headers.destination, frame.headers['destination'], or
      # frame.headers[:destination]
      def destination
        @headers.destination
      end

      # Returns the name of the subscription which is responsible for the
      # client having received this message.
      #
      # This is a convenience method for:
      # frame.headers.subscription, frame.headers['subscription'] or
      # frame.headers[:subscription]
      def subscription
        @headers.subscription
      end
    end
  end
end
